version: '3'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: ptcg
    volumes:
      - ./.data/pg:/var/lib/postgresql/data
      # - ./initdb/sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379

  swagger:
    image: swaggerapi/swagger-ui
    environment: 
      SWAGGER_JSON: "/documents/swagger.json"
    volumes:
      - ./documents:/documents
    ports:
      - 8080:8080
