# environment
env: dev

log:
  level: "debug" # trace, debug, info, warn, error, fatal, panic
  environment: dev
  format: "console"
  app_id: ptcg_trader
  # no_color: true

database:
  debug: true
  host: localhost
  port: 5432
  username: local
  password: local
  db_name: ptcg
  type: postgres
  search_path: "trader"
  ssl_enable: false

redis:
  addresses: [ "localhost:6379" ]
  password: ""
  max_retries: 5
  pool_size: 5
  db: 1

http:
  debug: true
  address: ":17420"

trader:
  # strategy: "redis_lock"
  strategy: "database_row_lock"
