# environment
env: dev

log:
  level: "error"
  environment: dev
  format: "console"
  app_id: ptcg_trader

database:
  debug: false
  host: postgres
  port: 5432
  username: local
  password: local
  db_name: ptcg
  max_idle_conns: 2
  max_open_conns: 5
  type: postgres
  search_path: "trader"
  ssl_enable: false

redis:
  addresses: [ "redis:6379" ]
  password: ""
  max_retries: 5
  pool_size: 5
  db: 1

http:
  debug: false
  address: ":17420"

trader:
  strategy: "database_row_lock"
