# Default values for gam-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: xiao4011/ptcg_trader
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

containers:
  command: ["./main"]
  args: ["server"]
  ports:
    - name: http
      containerPort: 17420
      protocol: TCP
  healthCheck:
    path: /ping 
    port: 17420
  volumeMountsPath: /server/config
  secretName: ptcg-trader-config

service:
  type: ClusterIP
  ports:
    - name: http
      port: 17420
      targetPort: 17420

livenessProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 15
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10
readinessProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 15
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10

env:
  - name: CONFIG_PATH
    value: "/server/config"

ingress:
  enabled: true
  host: "trader.ptcg.10oz.tw"
  tls:
    enabled: true
    secretName: trader-ptcg-10oz-tw-tls

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

secret:
  config: |
    env: prod

    log:
      level: "info"
      environment: prod
      format: "console"
      app_id: ptcg_trader
      no_color: true

    database:
      debug: true
      host: postgres-postgresql-headless.postgres.svc.cluster.local
      port: 5432
      username: not_local
      password: not_local
      db_name: ptcg
      max_idle_conns: 2
      max_open_conns: 5
      type: postgres
      search_path: "trader"
      ssl_enable: false

    redis:
      addresses: [ "redis-headless.redis.svc.cluster.local:6379" ]
      password: "why_we_need_password"
      max_retries: 5
      pool_size: 5
      db: 1

    http:
      debug: true
      address: ":17420"

    stan:
      debug: true
      address: ptcg-stan.stan.svc.cluster.local:4222
      cluster_id: "ptcg-stan"
      client_id: "trader"
      group_name: "ptcg"
