{{- if .Values.ingress.tls.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.ingress.tls.secretName }}-certificate
spec:
  dnsNames:
    - {{ .Values.ingress.host }}
  secretName: {{ .Values.ingress.tls.secretName }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
{{- end -}}  
