apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
{{- if not .Values.service.omitClusterIP }}
  {{ with .Values.service.clusterIP }}clusterIP: {{ . | quote }}{{ end }}
{{- end }}
  type: {{ .Values.service.type }}
  ports:
{{ toYaml .Values.service.ports | indent 2 }}
  selector:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
