// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockStan is an autogenerated mock type for the MockClient type
type MockStan struct {
	mock.Mock
}
