// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"
	model "ptcg_trader/pkg/model"

	mock "github.com/stretchr/testify/mock"

	repository "ptcg_trader/pkg/repository"

	service "ptcg_trader/pkg/service"
)

// MockMatcher is an autogenerated mock type for the Matcher type
type MockMatcher struct {
	mock.Mock
}

// MatchOrders provides a mock function with given fields: ctx, order
func (_m *MockMatcher) MatchOrders(ctx context.Context, order *model.Order) (*model.Order, error) {
	ret := _m.Called(ctx, order)

	var r0 *model.Order
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) *model.Order); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *model.Order) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithRepo provides a mock function with given fields: repo
func (_m *MockMatcher) WithRepo(repo repository.Repositorier) service.Matcher {
	ret := _m.Called(repo)

	var r0 service.Matcher
	if rf, ok := ret.Get(0).(func(repository.Repositorier) service.Matcher); ok {
		r0 = rf(repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.Matcher)
		}
	}

	return r0
}
