// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	context "context"
	model "ptcg_trader/pkg/model"

	mock "github.com/stretchr/testify/mock"

	repository "ptcg_trader/pkg/repository"

	service "ptcg_trader/pkg/service"

	testing "testing"
)

// MockMatcher is an autogenerated mock type for the Matcher type
type MockMatcher struct {
	mock.Mock
}

// AsyncMatchOrders provides a mock function with given fields: ctx, order
func (_m *MockMatcher) AsyncMatchOrders(ctx context.Context, order *model.Order) error {
	ret := _m.Called(ctx, order)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MatchOrders provides a mock function with given fields: ctx, order
func (_m *MockMatcher) MatchOrders(ctx context.Context, order *model.Order) (*model.Order, error) {
	ret := _m.Called(ctx, order)

	var r0 *model.Order
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) *model.Order); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *model.Order) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithRepo provides a mock function with given fields: repo
func (_m *MockMatcher) WithRepo(repo repository.Repositorier) service.Matcher {
	ret := _m.Called(repo)

	var r0 service.Matcher
	if rf, ok := ret.Get(0).(func(repository.Repositorier) service.Matcher); ok {
		r0 = rf(repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.Matcher)
		}
	}

	return r0
}

// NewMockMatcher creates a new instance of MockMatcher. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockMatcher(t testing.TB) *MockMatcher {
	mock := &MockMatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
