name: service deploy

on:
  push:
    branches:
      - master

jobs:
  go-test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: testing
        run: go test ./...

  build:
    needs: go-test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build image
        run: |
          docker buildx build \
            --push \
            --tag xiao4011/ptcg_trader:latest \
            --platform linux/amd64  . \
            -f deploy/docker/trader.dockerfile

  helm-deploy-trader:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: helm-deploy
        uses: 'deliverybot/helm@v1'
        with:
          helm: helm3
          release: trader
          chart: ./deploy/helm/charts/trader
          values: '${{ secrets.HELM_TRADER_VALUES }}'
          namespace: ptcg
          track: stable
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

  helm-deploy-matcher:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: helm-deploy
        uses: 'deliverybot/helm@v1'
        with:
          helm: helm3
          release: matcher
          chart: ./deploy/helm/charts/matcher
          values: '${{ secrets.HELM_MATCHER_VALUES }}'
          namespace: ptcg
          track: stable
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
